name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Archive Repository
        run: |
          zip -r deploy-artifact.zip .
        working-directory: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy-artifact
          path: deploy-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          ls
          cd src
          ls
          pwd
          # aws s3 sync /src s3://aahil-resume-001/
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  smoke_test:
    runs-on: ubuntu-latest
    needs: deploy
    environment:
      name: smoke_test

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy-artifact

      - name: Unzip Artifact
        run: |
          cd /home/runner/work/TCRC-Frontend/TCRC-Frontend
          unzip -o deploy-artifact.zip -d .
        shell: bash

      - name: Change Directory
        run: |
          cd /cypress/e2e
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
          browser: chrome
